import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import React, { useEffect } from "react";
import Layout from "../components/layout";
import { AppProvider } from "../context/context";
import { Provider as ReduxProvider } from "react-redux";
import { store } from "@/redux/store";
import "../public/css/line-awesome.min.css";
import "../public/css/modal-video.scss";
import { SessionContainer } from "@/components/session-container/SessionContainer";
import { ToastContainer } from "react-toastify";
import "../styles/global.css";
import "../styles/main.sass";
import "react-toastify/dist/ReactToastify.css";
import { TicketModal } from "@/components/modal/ticket-modal/TicketModal";
import { BasketModal } from "@/components/modal/basket-modal/BasketModal";

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  if (Component.getLayout) {
    return Component.getLayout(
      <AppProvider>
        <Head>
          <title>Carpatic Giveaways - Online Lotto & Lottery Reactjs</title>
          <meta name="description" content="Generated by Carpatic giveaways" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </AppProvider>,
    );
  }
  return (
    <AppProvider>
      <Head>
        <title>Carpatic Giveaways - Online Lotto & Lottery Reactjs</title>
      </Head>
      <ReduxProvider store={store}>
        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <TicketModal />
        <BasketModal />
        <SessionContainer>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </SessionContainer>
      </ReduxProvider>
    </AppProvider>
  );
}

export default MyApp;
